name: Quarto Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      # (Optional) Setup R if you render R code chunks
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      # (Optional) Install R packages your site needs
      # - name: Install R packages
      #   run: |
      #     R -q -e 'install.packages(c("rmarkdown","knitr"))'

      # If you use Python chunks, uncomment and add deps
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.x"

      - name: Render
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site